language: go

os:
  - linux
  - windows
  - osx

go:
  - 1.14

cache:
  directories:
    - .gomodrun/
    - $GOPATH/pkg/mod/

before_install:
  - |
      case $TRAVIS_OS_NAME in
        windows)
          choco install -y make busybox
          ;;
      esac

install:
  - go mod download
  - |
    GOMODRUN_VERSION=$(cat VERSION)
    OS_NAME="$TRAVIS_OS_NAME"

    if [[ "$OS_NAME" == "osx" ]]; then
      OS_NAME="darwin"
    fi

    mkdir -p "$GOPATH/bin/"
    if [[ "$OS_NAME" == "windows" ]]; then
      curl -L -o "$HOME/gomodrun.zip" "https://github.com/dustinblackman/gomodrun/releases/download/v${GOMODRUN_VERSION}/gomodrun_${GOMODRUN_VERSION}_${OS_NAME}_amd64.zip"
      busybox unzip -d "$GOPATH/bin/" "$HOME/gomodrun.zip"
    else
      curl -L "https://github.com/dustinblackman/gomodrun/releases/download/v${GOMODRUN_VERSION}/gomodrun_${GOMODRUN_VERSION}_${OS_NAME}_amd64.tar.gz" | tar -zxvf - -C "$GOPATH/bin/" gomodrun
    fi

script:
  - |
      case $TRAVIS_OS_NAME in
        linux)
          make lint
          ;;
      esac
  - make test-coverage
  - gomodrun --tidy
