language: go

go:
- 1.13

addons:
 snaps:
   - gomodrun

cache:
  directories:
    - .gomodrun/
    - /home/travis/gopath/pkg/mod/
install:
  - go mod download
script:
 - make lint
 - make test-coverage
